
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scope
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

jwt:
  secret: "super-secret-key-super-secret-key"
  expiration: 86400000

kind: Application